# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-29 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita', models.CharField(max_length=512)),
                ('introducao', models.CharField(max_length=2018)),
                ('ingredientes', models.CharField(max_length=2048)),
                ('preparo', models.CharField(max_length=2048)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media')),
                ('autor', models.CharField(max_length=512)),
            ],
        ),
    ]
